[package]
name = "iracing-broadcast-wasm"
version = "0.1.0"
description = "WASM bindings crate for iracing-broadcast."
authors.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
iracing-broadcast = { path = "../iracing-broadcast" }
